"""initial schema

Revision ID: 389ac8b70bec
Revises: 
Create Date: 2026-08-26 08:39:13.571687

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '389ac8b70bec'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('farms',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('location_region', sa.String(length=255), nullable=False),
    sa.Column('capacity', sa.Integer(), nullable=False),
    sa.Column('supervisor_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_farms_supervisor_id'), 'farms', ['supervisor_id'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('admin', 'field_hand', 'auditor', name='user_role', native_enum=False, length=32), nullable=False),
    sa.Column('farm_id', sa.Uuid(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['farm_id'], ['farms.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_farm_id'), 'users', ['farm_id'], unique=False)
    op.create_foreign_key(
        'fk_farms_supervisor_id',
        'farms',
        'users',
        ['supervisor_id'],
        ['id'],
        ondelete='SET NULL',
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('actor_id', sa.Uuid(), nullable=True),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('entity_type', sa.String(length=64), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('details', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_created_at'), 'audit_logs', ['created_at'], unique=False)
    op.create_table('equipment',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('serial_number', sa.String(length=128), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('status', sa.Enum('Idle', 'In-Use', 'Maintenance', 'Retired', name='equipment_status', native_enum=False, length=32), nullable=False),
    sa.Column('fuel_level', sa.Integer(), nullable=False),
    sa.Column('facility_id', sa.Uuid(), nullable=False),
    sa.Column('assigned_operator_id', sa.Uuid(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('fuel_level >= 0 AND fuel_level <= 100', name='ck_equipment_fuel_level'),
    sa.ForeignKeyConstraint(['assigned_operator_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['facility_id'], ['farms.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_equipment_assigned_operator_id'), 'equipment', ['assigned_operator_id'], unique=False)
    op.create_index(op.f('ix_equipment_facility_id'), 'equipment', ['facility_id'], unique=False)
    op.create_index(op.f('ix_equipment_model'), 'equipment', ['model'], unique=False)
    op.create_index(op.f('ix_equipment_serial_number'), 'equipment', ['serial_number'], unique=True)
    op.create_table('field_jobs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=False),
    sa.Column('priority', sa.Enum('Low', 'Medium', 'Critical', name='job_priority', native_enum=False, length=32), nullable=False),
    sa.Column('status', sa.Enum('Pending', 'In-Progress', 'Completed', 'Failed', name='job_status', native_enum=False, length=32), nullable=False),
    sa.Column('equipment_id', sa.Uuid(), nullable=False),
    sa.Column('operator_id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['operator_id'], ['users.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_field_jobs_equipment_id'), 'field_jobs', ['equipment_id'], unique=False)
    op.create_index(op.f('ix_field_jobs_operator_id'), 'field_jobs', ['operator_id'], unique=False)
    op.create_index(op.f('ix_field_jobs_status'), 'field_jobs', ['status'], unique=False)
    op.create_table('service_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('field_job_id', sa.Uuid(), nullable=False),
    sa.Column('file_url', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['field_job_id'], ['field_jobs.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_service_reports_field_job_id'), 'service_reports', ['field_job_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_service_reports_field_job_id'), table_name='service_reports')
    op.drop_table('service_reports')
    op.drop_index(op.f('ix_field_jobs_status'), table_name='field_jobs')
    op.drop_index(op.f('ix_field_jobs_operator_id'), table_name='field_jobs')
    op.drop_index(op.f('ix_field_jobs_equipment_id'), table_name='field_jobs')
    op.drop_table('field_jobs')
    op.drop_index(op.f('ix_equipment_serial_number'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_model'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_facility_id'), table_name='equipment')
    op.drop_index(op.f('ix_equipment_assigned_operator_id'), table_name='equipment')
    op.drop_table('equipment')
    op.drop_index(op.f('ix_audit_logs_created_at'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_constraint('fk_farms_supervisor_id', 'farms', type_='foreignkey')
    op.drop_index(op.f('ix_users_farm_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_farms_supervisor_id'), table_name='farms')
    op.drop_table('farms')
    # ### end Alembic commands ###
